# Generated by Django 4.1.2 on 2022-12-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
