# Generated by Django 4.1.2 on 2022-12-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
    ]
