# Generated by Django 4.1.2 on 2022-11-23 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='transaction_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
