# Generated by Django 4.1.2 on 2022-12-05 11:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Inflow', 'Inflow'), ('Outflow', 'Outflow')], max_length=9)),
                ('category', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_destination', to='account.account')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_source', to='account.account')),
            ],
        ),
    ]
